
rady:
  mysql:
    host: localhost
    utf-8: true
  redis:
    host: 127.0.0.1
    port: 6937
  jwt:
    start: 2018-1-30 00:00:00
  server:
    ports:
      - 80
      - 443
    ready:
      - true
      - false
    starts:
      - 2018-1-30 00:00:00
      - 2018-1-30 00:00:00
